### ISSUE TITLE
Peer Review Lab09 - Filippo Greco (s309529)

### ISSUE THREAD

**Issue by figimodi** [ivanmag22/computational-intelligence#3]
## Code Readability
The readme/markdown and the code itself is well written and i could understand quickly the strategies you have tried during your work.

## Strategies
I can relate with the strategies you've tried. I think these were valid tries and, as far as the strategies i've implemented too, i can confirm your results (i.e. islands model doesn't improve the algorithm). I agree with you with the numbers of individuals/offsprings as well. It is clear that you worked a good amount of time on this lab but unfortunately didn't find a clear solution, to this regard i can tell most of the students felt lost not finding an ultimate "best strategy". 

## Results
I couldn't find a clear representation of the results, i was only able to find an estimation of instance 1 by looking at the output of the code.
For this reason i suggest you to implement few lines of code that would plot the results for all the instances.

With this being said, i would value your overall work with a positive feedback.

**Comment by ivanmag22** [comment]
Hi Filippo!
You are right for the representation of the results, they are not so clear! Next time I will try to plot how the results improve over the generations.

Thank you for the peer review and for the advices!
